// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ixzksyogrrzqzsqbsrtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4emtzeW9ncnJ6cXpzcWJzcnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2Mjc0NDksImV4cCI6MjA3NjIwMzQ0OX0.mqNrdcwgg8nMpgDLJjqDGOWL_vO4SngZ7IIs8LbOhls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);