on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx (required for multi‑arch)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry (or Docker Hub)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cpap-tracker:latest
          platforms: linux/arm64
          # Temporarily disable cache to force a rebuild with the new Dockerfile instructions.
          # You can remove the `no-cache` line after this build succeeds.
          no-cache: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cpap-tracker:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cpap-tracker:cache,mode=max